#pragma once

#include "lib/utils/enum.h"

MAKE_ENUM(PacketType, uint8_t,
    POWER, 0x01,

    SENSOR_VALUE, 0x10,
    CONTROL_VALUE, 0x11,
    HISTORY_DATA, 0x12,

    NIGHT_MODE_ENABLED, 0x20,
    NIGHT_MODE_START, 0x21,
    NIGHT_MODE_END, 0x22,

    SENSOR_TYPE, 0x30,
    SENSOR_DATA, 0x31,

    CONTROL_TYPE, 0x32,
    CONTROL_DATA, 0x33,

    PID_TARGET, 0x40,
    PID_P, 0x41,
    PID_I, 0x42,
    PID_D, 0x43,
    PID_INTERVAL, 0x44,
    PID_REVERSE, 0x45,

    SYS_CONFIG_MDNS_NAME, 0x60,

    SYS_CONFIG_WIFI_MODE, 0x61,
    SYS_CONFIG_WIFI_SSID, 0x62,
    SYS_CONFIG_WIFI_PASSWORD, 0x63,
    SYS_CONFIG_WIFI_CONNECTION_CHECK_INTERVAL, 0x64,
    SYS_CONFIG_WIFI_MAX_CONNECTION_ATTEMPT_INTERVAL, 0x65,

    SYS_CONFIG_STEPPER_1_PIN, 0x66,
    SYS_CONFIG_STEPPER_2_PIN, 0x67,
    SYS_CONFIG_STEPPER_3_PIN, 0x68,
    SYS_CONFIG_STEPPER_4_PIN, 0x69,
    SYS_CONFIG_STEPPER_EN_PIN, 0x6A,

    SYS_CONFIG_TIME_ZONE, 0x6C,

    SYS_CONFIG_MQTT_ENABLED, 0x70,
    SYS_CONFIG_MQTT_HOST, 0x71,
    SYS_CONFIG_MQTT_PORT, 0x72,
    SYS_CONFIG_MQTT_USER, 0x73,
    SYS_CONFIG_MQTT_PASSWORD, 0x74,
    SYS_CONFIG_MQTT_CONVERT_BRIGHTNESS, 0x75,

    SYS_CONFIG_ENDSTOP_PIN, 0x81,
    SYS_CONFIG_ENDSTOP_HIGH_STATE, 0x82,

    GET_CONFIG, 0xa0,
    GET_STATE, 0xa1,
    RESTART, 0xb0,

    // Controls

    PWM_CONTROL_PIN, 0xc0,
    PWM_CONTROL_PERIOD, 0xc1,

    // Sensors

    ANALOG_SENSOR_PIN, 0xe0,
    ANALOG_SENSOR_RESOLUTION, 0xe1,

    DSX18_SENSOR_PIN, 0xe2,
    DSX18_SENSOR_RESOLUTION, 0xe3,
    DSX18_SENSOR_PARASITE, 0xe4,
)
